cert-mounter-blueprint:
  namespace: "rtd"
  nameOverride: ""
  fullnameOverride: ""

  deployment:
    create: true

  kvCertificatesName:
    - mock-certificate
    - fake-cert
    - dev01-rtd-internal-dev-cstar-pagopa-it

  keyvault:
    name: "cstar-p-rtd-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
